[versions]
kotlin = "2.3.10"
agp = "8.11.1"
composeMultiplatform = "1.11.1"
material3Expressive = "1.11.0-alpha07"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-coreKtx = "1.16.0"
androidx-lifecycle = "2.9.1"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
androidx-glance = "1.1.1"
dbus-java = "5.2.0"
jna = "5.16.0"

[libraries]
compose-multiplatform = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
compose-material3-expressive = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3Expressive" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation" }
compose-ui = { module = "org.jetbrains.compose.ui:ui" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
dbus-java-core = { module = "com.github.hypfvieh:dbus-java-core", version.ref = "dbus-java" }
dbus-java-unixsocket = { module = "com.github.hypfvieh:dbus-java-transport-native-unixsocket", version.ref = "dbus-java" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
